name: nravepay
description: Nravepay is a package that makes accepting card payments in a flutter project easier using Flutterwave.
homepage: https://github.com/nelstein/nravepay

version: 1.2.3


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  equatable: ^2.0.3
  websafe_svg: ^2.1.1
  tripledes_nullsafety: ^1.0.3
  intl: ^0.17.0
  get_it: ^7.2.0
  webview_flutter: ^3.0.1
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  async: ^2.8.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
