name: nravepay
description: Nravepay is a package that makes accepting card payments in a flutter project easier using Flutterwave.
homepage: https://github.com/nelstein/nravepay

version: 1.0.6


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter_svg: ^0.22.0
  tripledes_nullsafety: ^1.0.1
  intl: ^0.17.0
  get_it: ^6.0.0
  webview_flutter: ^2.0.2
  async: ^2.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
