name: Publish to Pub.dev

on: [push, pull_request]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!
        
      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ OAUTH_REFRESH_TOKEN }}
